-- ==============================
-- 1. TABLESPACES
-- ==============================

CREATE TABLESPACE davax_data
DATAFILE 'davax_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE davax_data
DATAFILE 'davax_data_v2.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE davax_index
DATAFILE 'davax_index_v2.dbf' SIZE 50M AUTOEXTEND ON NEXT 5M EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE davax_partition
DATAFILE 'davax_partition_v2.dbf' SIZE 200M AUTOEXTEND ON NEXT 20M EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE davax_archive
DATAFILE 'davax_archive_v2.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE davax_audit
DATAFILE 'davax_audit_v2.dbf' SIZE 50M AUTOEXTEND ON NEXT 5M EXTENT MANAGEMENT LOCAL;

